### ISSUE TITLE
Unexpected EEx.Engine state

### ISSUE THREAD

**Issue by HarshBalyan** [CrowdHailer/eex_html#10]
I am trying to update elixir from 1.7.4 to 1.16.2.
I am running into a compilation error.
```
Compilation error in file lib/myapp/api/actions/support/some_action.ex ==
** (RuntimeError) unexpected EEx.Engine state: {{:., [], [{:__aliases__, [alias: false], [:EExHTML]}, :raw]}, [], [[]]}. This typically means a bug or an outdated EEx.Engine or tool
    (eex 1.16.2) lib/eex/engine.ex:218: EEx.Engine.check_state!/1
    (eex 1.16.2) lib/eex/engine.ex:181: EEx.Engine.handle_text/3
    (eex 1.16.2) lib/eex/compiler.ex:321: EEx.Compiler.generate_buffer/4
    (raxx_view 0.1.7) expanding macro: Raxx.View.__using__/1
    lib/myapp/api/actions/support/some_action:6: SomeAction (module)
    (elixir 1.16.2) expanding macro: Kernel.use/2
    lib/myapp/api/actions/support/some_action.ex:6: SomeAction (module)
    expanding macro: MyApp.API.SupportLayout.__using__/1
```

I have an action like 
```elixir
def SomeAction
  ...
    use MyApp.API.SupportLayout,
    arguments: [:transaction],
    template: Path.join(__DIR__, "transaction.html.eex")

...
end
```

Support Layout
```elixir
defmodule MyApp.API.SupportLayout do
  use Raxx.View.Layout,
    optional: [
      page_title: "Admin",
      with_navbar: true,
      message: nil,
      message_type: "info"
    ]
end
```

`EEx.Engine.check_state!/1` expects `%{binary: _, dynamic: _, vars_count: _}` which was added in Elixir v1.8.
`EExHTML.Engine.init/1` doesn't set any of these params.

**Comment by HarshBalyan** [comment]
Not sure if it's the best way but I've made it work for myself after making [these changes](https://github.com/HarshBalyan/eex_html/commit/4e7b4da9401b4627e888d027c488f100b903698a).
Let me know if it's good to go, I'll raise a PR.
@CrowdHailer @ejc123

**Comment by CrowdHailer** [comment]
I'm not actively maintaining this. But if you open a PR I'll try and look over it

**Comment by HarshBalyan** [comment]
@CrowdHailer please, take a look at #11
